### ISSUE TITLE
Uncaught TypeError: Cannot read property 'renderer' of undefined

### ISSUE THREAD

**Issue by pitaj** [jonschlinkert/remarkable#116]
The browser file isn't working. I keep getting this error:

```
Uncaught TypeError: Cannot read property 'renderer' of undefined
```

I seems to be occurring on the line: 

```
return this.renderer.render(this.parse(src, env), this.options, env);
```

Which is weird because `this` should be defined under any situation, right?

I must be doing something wrong. I've even tried older versions from the CDN. What is going on?

**Comment by mohiniyadav** [comment]
i am getting error  Uncaught TypeError: Cannot read property 'rendering' of undefined in fusionchart.js 
how to resolve it?

**Comment by mohiniyadav** [comment]
Please help?

**Comment by jonschlinkert** [comment]
@mohiniyadav create a new issue with a complete code example and all necessary information to reproduce the bug.
