### ISSUE TITLE
Changelog is missing an entry for v1.6.0

### ISSUE THREAD

**Issue by cvrebert** [jonschlinkert/remarkable#126]

**Comment by nikolas** [comment]
Also, the version of remarkable in the `dist/` dir in the 1.6 tarball is still at 1.5.0.

**Comment by jonschlinkert** [comment]
Sorry, been at codemash this week, I forgot about this when I made my last comment. I'll have to get caught up when I get back.

**Comment by cvrebert** [comment]
@jonschlinkert Ping.

**Comment by jonschlinkert** [comment]
Really sorry for the delay. Been working on deadlines with non-OS projects but I've been getting caught up over the past few days. This project is important to me, I'll get it updated.

**Comment by TrySound** [comment]
New releases out with detailed changelog
