### ISSUE TITLE
cpu 100% on render with html = true

### ISSUE THREAD

**Issue by fengmk2** [jonschlinkert/remarkable#127]
Repeat codes:

``` js
var Remarkable = require('remarkable');
var md = new Remarkable();
md.set({
  html: true
});

var content = 'foo <!--- This is what the user will see during the configuration ->';
md.render(content);
```

Debug this find out `HTML_TAG_RE: /^(?:<[A-Za-z][A-Za-z0-9]*(?:\s+[a-zA-Z_:][a-zA-Z0-9:._-]*(?:\s*=\s*(?:[^"'=<>`\x00-\x20]+|'[^']_'|"[^"]_"))?)_\s_\/?>|<\/[A-Za-z][A-Za-z0-9]_\s_>||<[?]._?[?]>|<![A-Z]+\s+[^>]_>|<![CDATA[([^]]+|][^]]|]][^>])*]]>)/` cause this problem.

So simple repeat codes is 

``` js
'foo <!--- This is what the user will see during the configuration ->'.match(HTML_TAG_RE);
```

![image](https://cloud.githubusercontent.com/assets/156269/5597899/6f22118a-92e6-11e4-9269-70e18b03a01d.png)

**Comment by jonschlinkert** [comment]
the invalid code comment is the problem. the closing bracket is missing a dash `->`. I can see how that regex might be able to be improved, but really this is a linting issue. Or are you also having the issue with valid HTML?

**Comment by jonschlinkert** [comment]
let me know if I'm missing something, I hope my previous comment doesn't sound dismissive

**Comment by fengmk2** [comment]
The invalid markdown create by user, we can't change it before render.

But the problem is why this invalid code comment cause too much cpu. I think remarkable need to handle this.

**Comment by jonschlinkert** [comment]
makes sense, I'll take a look.

**Comment by fengmk2** [comment]
thanks

**Comment by jonschlinkert** [comment]
what version of remarkable are you using? the regex is different in latest

**Comment by fengmk2** [comment]
https://github.com/jgm/CommonMark/issues/263

**Comment by SohumB** [comment]
There's a similar problem (in remarkable 1.6.2) that I've managed to reproduce. 

```js
var Remarkable = require('remarkable');
var md = new Remarkable();
md.set({
  html: true
});

md.render("before <!-- user opens a comment but forgets to close it more text more text <!-- comment in block --> after text after text");
```

This is an infinite loop on my machine, and it's a common enough case in live editing scenarios when a user is in the middle of creating a new comment before existing comments.

Thanks!
