### ISSUE TITLE
Would a pull request that adds notation information to some tokens be welcome?

### ISSUE THREAD

**Issue by marijnh** [jonschlinkert/remarkable#128]
I'm building a tool that uses Remarkable's parser to build up an AST, then does some stuff with that AST, and reserializes it. I'd like to have the resulting output be as close to the input as possible, but it currently is somewhat awkward to find out things like

 - Which bullet character was used for a bullet list
 - Whether strong/em spans used asterisks or underscores around the text
 - Whether a header uses ATX or Setext style
 - Whether a link used inline syntax or defined a separate reference

These can be made much easier by having some extra properties on the corresponding tokens. If you have no problem with this, I'll submit a simple pull request to extend these tokens.

**Comment by sbruchmann** [comment]
Just wondering why you closed this issue, @marijnh. I’m interested in this too!

**Comment by leeoniya** [comment]
my hope is that @marijnh's building a markdown AST <> html AST so they can be edited interchangeably in a side-by-side codemirror/WYSIWYG setup :)

i've done something in the same ballbark with reMarked.js [1]... demo integration with redactor: [2], fork: [3], lots of discussions about this goal [4].

[1] https://github.com/leeoniya/reMarked.js
[2] https://leeoniya.github.io/redactor-js/
[3] https://github.com/leeoniya/redactor-js/tree/markdown-panel
[4] https://github.com/html5cat/redactor-js/issues/2

**Comment by sbruchmann** [comment]
@leeoniya Oh, wow. Exactly what I was looking for! Thank you!

**Comment by marijnh** [comment]
I closed this because I've decided to use https://github.com/markdown-it/markdown-it instead.

I may indeed be trying to pull of such an editor, but whether it is going to work, and whether the customer who I'm writing it for will open-source it, remains to be seen.
