### ISSUE TITLE
Why do \n need to be preceded by two spaces?

### ISSUE THREAD

**Issue by dj-hedgehog** [jonschlinkert/remarkable#133]
Why does remarkable only render a <br> when an \n is preceded by two spaces?

At first I thought I messed up something but it's the same as in the remarkable-demo http://jonschlinkert.github.io/remarkable/demo/

**Comment by jonschlinkert** [comment]
closed based on #140

**Comment by jonschlinkert** [comment]
also, I'll look at gfm/commonmark spec again and change readme if necessary. thanks
