### ISSUE TITLE
Trying to indent multiple lines selection with TAB causes selected lines to disappear

### ISSUE THREAD

**Issue by danidemi** [jonschlinkert/remarkable#137]
Sometimes I paste a piece of code inside Remarkable, then, since I would like it to be rendered as code, I select all the lines and I hit TAB. I would expect the selected lines to move right by one tab, but instead they just disappear.

It is really annoying if you have to TAB multiples lines one by one, when the piece of code is longer than an handful of lines.

Anyhow, thanks for your work, I really appreciate Remarkable.

**Comment by jonschlinkert** [comment]
is this happening in your test editor? it does't sound related to remarkable

**Comment by danidemi** [comment]
Doh! It turned out I posted the bug to the wrong "remarkable". I really intended <http://remarkableapp.net/>!
Sorry!
