### ISSUE TITLE
GFM style line breaks

### ISSUE THREAD

**Issue by dj-hedgehog** [jonschlinkert/remarkable#140]
The README says remarkable is intended to be close to GFM yet line-breaks need to preceeded by two spaces. GFM needs no additional spaces before a line-break.

Is this intentional?
Can this be changed?

**Comment by dj-hedgehog** [comment]
Whoops, I didn't mean to create a seperate issue.
This is a duplicate form https://github.com/jonschlinkert/remarkable/issues/133.

**Comment by vyp** [comment]
Doesn't `breaks: true` do what you're looking for?

It might be intentional in that commonmark [recommends](http://spec.commonmark.org/0.17/#soft-line-breaks) it, but you're right in that the readme says it should be similar to gfm, so I'm not sure.

**Comment by dj-hedgehog** [comment]
Ah thanks, that was exactly what I was looking for <3
