### ISSUE TITLE
German umlauts break conversion

### ISSUE THREAD

**Issue by southdesign** [jonschlinkert/remarkable#144]
The conversion of the german word for exercise:

    # Übung

is converted to:

    <h1 id="-bung-1">Ãœbung 1</h1>

when no charset is given. With the `<meta charset="UTF-8">` it is converted to:

    <h1 id="-bung-1">Übung 1</h1>

where the id is wrong and should be `übung-1` instead of `-bung-1`.

In any way, the Ü (German umlauts) break the conversion. They work out of the box in any standard HTML5 document when entered directly (with meta charset absent).

**Comment by jonschlinkert** [comment]
thanks for the heads up

**Comment by southdesign** [comment]
I'm very sorry, but I confused `remarkable` with `marked`. I previously had used `remarkable`, but this bug is present in `marked` - not `remarkable`.

I'll probably switch now.

Sorry to bother!

**Comment by jonschlinkert** [comment]
ha, no worries. thanks for the follow up
