### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by MalcolmMielle** [jonschlinkert/remarkable#156]
It would be great to have some way to open multiple file in different tabs.

Thanks a lot

**Comment by vyp** [comment]
Similar to #143, I believe you have confused two different projects (although I do not blame you).

**Comment by MalcolmMielle** [comment]
Hooo yeah. Dang it, sorry sorry sorry :S

**Comment by jonschlinkert** [comment]
@vyp thanks for clarifying!
