### ISSUE TITLE
Preview and editor windows size

### ISSUE THREAD

**Issue by MalcolmMielle** [jonschlinkert/remarkable#157]
I think it would be good if the size of Preview and Editor windows where proportional. If I tile them on my screen (let's say so it takes the left half) I need to resize the preview windows everytime because it's shrink.

Before
![screenshot from 2015-05-20 15 48 05](https://cloud.githubusercontent.com/assets/4457840/7727204/a8a0228e-ff07-11e4-8d2a-e196974211b8.png)

After
![screenshot from 2015-05-20 15 48 15](https://cloud.githubusercontent.com/assets/4457840/7727206/aa085984-ff07-11e4-8722-c5eee5de5802.png)

thanks a lot :)

**Comment by vyp** [comment]
#156.

**Comment by jonschlinkert** [comment]
thanks again @vyp. and no worries @MalcolmMielle
