### ISSUE TITLE
Scrolling wraps in live preview

### ISSUE THREAD

**Issue by kford** [jonschlinkert/remarkable#162]
When scrolling up (in live preview), when I reach the top of my live preview it scolls back to the bottom, in effect giving me vertical scroll wrapping.  The vertical scroll wrapping does not occur when scrolling down.

version - 1.41
OS: UbuntuGnome 14.04

**Comment by Salamandar** [comment]
I had this annoying bug some time ago, but it seems it's been solved (I'm using 1.62 there, on ArchLinux).

**Comment by doowb** [comment]
@kford this is a markdown parser. You're looking for the remarkable app.
