### ISSUE TITLE
Violent scrolling on GTK app

### ISSUE THREAD

**Issue by Salamandar** [jonschlinkert/remarkable#165]
Hi there !
I'm using the GTK app, and when I'm typing (without changing lines), the MD preview often scrolls violently to the top of the document then back where I was typing. That's not very comfortable when typing while reading the preview… :p

Salamandar

**Comment by doowb** [comment]
Hi @Salamandar this repository is for a markdown parser. You're looking for a markdown editor app (I'm not able to find a reliable link for it).
