### ISSUE TITLE
Strikethrough does not render

### ISSUE THREAD

**Issue by rumtscho** [jonschlinkert/remarkable#167]
I tried using the double-tilde syntax, which as far as I can tell is enabled in Remarkable. Even when inserted by Remarkable's own Strikethrough button, it is not rendered in the preview, nor correctly tagged in the HTML export. 

Version 1.62 running on Fedora Twenty One, KDE spin, kernel 4.1.6-100.fc21.x86_64. 

![selection_018](https://cloud.githubusercontent.com/assets/3685920/9819214/041f4f3c-58ad-11e5-816b-9adb0c50c7d8.png)

**Comment by doowb** [comment]
@rumtscho looks like you're looking for the remarkable app: https://github.com/remarkableapp/Remarkable-Linux

**Comment by rumtscho** [comment]
Ah, sorry for that. I guess I didn't see the wood for the trees. Thanks for sending me to the right place.
