### ISSUE TITLE
plugin: table of contents (toc)

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/remarkable#17]
TOC generation is something that should be done with a remarkable plugin, not supported directly. 

There are so many different approaches to implementing a table of contents, with so many different options, I'd rather focus  on making it easier for implementors to create their own TOC plugins for remarkable.

@puzrin thoughts? feel free to close this when you have a decision.

**Comment by dmr** [comment]
So what is the solution nowadays for this problem?

**Comment by jonschlinkert** [comment]
@dmr, see https://github.com/jonschlinkert/markdown-toc
