### ISSUE TITLE
[feature request] Option to create links with target=_blank

### ISSUE THREAD

**Issue by wmertens** [jonschlinkert/remarkable#171]
Would it be possible to add an option so all links get the `target=_blank` attribute?

I'm using React and going through the DOM to edit `<a>` nodes is Not Done, and string replace is error prone...

**Comment by jonschlinkert** [comment]
hmm, I think this would actually be pretty easy with a plugin. let me try to put an example together

**Comment by DiscoNova** [comment]
Umm... you know you have full access to the renderer, right? Just override the link_open -handler (or whatever it is called, can't remember off the top of my head) and have it return HTML with the preferred attribute :-p

**Comment by wmertens** [comment]
sounds good, do you know of any documentation?

**Comment by jonschlinkert** [comment]
> Just override the link_open -handler 

yeah that's what I meant, but it can be sugar-coated to be a plugin ;) 

> sounds good, do you know of any documentation?

here is plugin I created that overrides most of the renderer methods https://github.com/jonschlinkert/pretty-remarkable. it doesn't need to be a plugin, as @DiscoNova points out, but you can see how it works...

**Comment by DiscoNova** [comment]
Something not entirely unlike like this would probably work (without checking any documentation, completely untested, most likely contains tons of syntax errors and invalid naming:)

```javascript
import Remarkable from 'remarkable';
// ...import functions escapeHtml / replaceEntities also somewhere here...

export default function html(markdownSource, remarkableOptions) {

	const remarkable = new Remarkable(remarkableOptions);

	remarkable.renderer.rules.link_open = function (tokens, idx /*, options, env */) {
		var title = tokens[idx].title ? (' title="' + escapeHtml(replaceEntities(tokens[idx].title)) + '"') : '';
		return '<a target="_blank" href="' + escapeHtml(tokens[idx].href) + '"' + title + '>';
	};

	return remarkable.render(markdownSource);
}
```

**Comment by DiscoNova** [comment]
@jonschlinkert ... heh, looks like our clocks are synchronized :D both of my earlier messages were written without seeing your response before clicking "Comment" ;)

**Comment by wmertens** [comment]
For future reference, the link_open definition is at https://github.com/jonschlinkert/remarkable/blob/7318212b84f1cbb3e879158b36c465e416f7f396/lib/rules.js#L155-L158

How about adding a linkTarget option that the default rule can use, so people don't need to duplicate the link code?

Perhaps simply
```js
rules.link_open = function (tokens, idx, options /*, env */) {
  var title = tokens[idx].title ? (' title="' + escapeHtml(replaceEntities(tokens[idx].title)) + '"') : '';
  var target = options.linkTarget ? (' target="' + options.linkTarget + '"') : '';
  return '<a href="' + escapeHtml(tokens[idx].href) + '"' + title + target + '>';
};
```

**Comment by jonschlinkert** [comment]
@wmertens not a bad idea. Want to do a pr?

@DiscoNova sorry I didn't see your last two replies! probably b/c we replied at about the same time lol

**Comment by maerzhase** [comment]
did u imlpement that yet? i can't get it working. if i add the rule it complains that escapeHtml is not defined.

**Comment by pkfladset** [comment]
Support for this was added in 1.6.2 which was released today. Missed to updated the README file with description of the new configuration option, but will fix that later. 

To be able to use this feature set options.linkTarget to your desired link target

**Comment by wmertens** [comment]
Cool, thanks!!!

**Comment by karlguillotte** [comment]
It is a great feature and it is working well! Thanks! 

Perhaps, the `linkTarget` option could be a function as well. In that case, we would be able to test the URL and return an appropriate target.
