### ISSUE TITLE
'remarkable' now deprecated?

### ISSUE THREAD

**Issue by p2peditor** [jonschlinkert/remarkable#193]
If this quote from https://github.com/markdown-it/markdown-it is accurate:

    markdown-it is the result of the decision of the authors who contributed to 99% of the Remarkable
    code to move to a project with the same authorship but new leadership (Vitaly and Alex). It's not a fork.

does that now mean remarkable is deprecated or no longer being maintained? If so, the issue here is to put some kind of big, obvious note to that effect on the front page of https://github.com/jonschlinkert/remarkable

**Comment by jonschlinkert** [comment]
Nope, it's not, which is very easy to see by the recent commit history. markdown-it violates remarkable's copyright. This is the official repo that was originally created based on code that [I wrote for remarked](https://github.com/jonschlinkert/remarked), which was itself a refactor of marked.  

This quote is more accurate:

> don't believe what you read on t-shirts and the internet

please keep issues focused on bugs or feature requests. or if you'd like to contribute, that's great too. please no more time wasters
