### ISSUE TITLE
Settings values order randomly change in remarkable.settings

### ISSUE THREAD

**Issue by simondubois** [jonschlinkert/remarkable#194]
Hi,

Thank for the great native application that you have developed.

I am facing an issue with version 1.62 under Ubuntu 14.04.
Setting sorting in configuration file ~/.remarkable/remarkable.settings is inconsistent.
That is, the order is not the same between two application launches.
It is quite annoying as I am sharing my setup between computers with github.

Is it possible to sort the values by key (for example) before saving settings to file ?
Thank you for your help,

**Comment by jonschlinkert** [comment]
wrong remarkable
