### ISSUE TITLE
Math expression

### ISSUE THREAD

**Issue by shd101wyy** [jonschlinkert/remarkable#206]
Hello,

First of all, **thanks for the awesome library.**

I am writing an atom packages using remarkable 

https://atom.io/packages/atom-markdown-katex

I want to support math expression rendering in my markdown file.

For example:

```md
$x + 1$
$$ sin(x) + 1 $$
```

So is there any way to extend remarkable to support `$...math exp..$` and `$$...math exp...$$`.

Thanks ;)

**Comment by shd101wyy** [comment]
I think it shouldn't be very hard.

But any example how to implement it?

**Comment by shd101wyy** [comment]
nvm, I have figured out how to do that ;)

**Comment by satahippy** [comment]
@shd101wyy, could you share it with us?)

**Comment by shd101wyy** [comment]
@satahippy check [this line](https://github.com/shd101wyy/mume/blob/master/src/markdown-engine.ts#L340).

**Comment by satahippy** [comment]
@shd101wyy thank you!
Have you tried https://github.com/bradhowes/remarkable-katex ?

**Comment by shd101wyy** [comment]
@satahippy Yes. But I have switched to markdown-it now.
