### ISSUE TITLE
Raw <h1>–<h6> tags being wrapped with <p>

### ISSUE THREAD

**Issue by shannonmoeller** [jonschlinkert/remarkable#219]
Manually added `<h1>`–`<h6>` tags are being wrapped in `<p>` tags.

``` markdown
# Remarkable

<h2 id="foo">Foo</h2>

<div id="bar">Bar</div>

World
```

``` html
<h1>Remarkable</h1>
<p><h2 id="foo">Foo</h2></p>
<div id="bar">Bar</div>
<p>World</p>
```

![image](https://cloud.githubusercontent.com/assets/155164/16522759/a93bfa54-3f6d-11e6-8793-64a71f9f4241.png)

**Comment by scott-wyatt** [comment]
Did you find a fix for this? I also need this.

**Comment by shannonmoeller** [comment]
I switched to https://github.com/markdown-it/markdown-it.
