### ISSUE TITLE
.hljs class for highlightjs is not getting added to <pre> element

### ISSUE THREAD

**Issue by Kannaj** [jonschlinkert/remarkable#224]
I'm using highlight.sj like the below

```
const md = new Remarkable({
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(lang, str).value;
      } catch (err) {}
    }

    try {
      return hljs.highlightAuto(str).value;
    } catch (err) {}

    return ''; 
  }
});
```

As you can see , its exactly what was specified in the docs (perhaps i should be including something extra)

everything works fine except .hljs class not being added to the pre tag in a code style markdown. This is what highlight js looks for to add the background for the markdown. Manually adding the .hljs class in my html solves the issue so the problem is that its not getting added through remarkable.

Is there anything i should be adding to the above code?

**Comment by albermav** [comment]
You could add in remarkable options:
`langPrefix: 'hljs language-'`

**Comment by Kannaj** [comment]
Thank you :)

**Comment by hramos** [comment]
Please note that the `langPrefix` workaround only works if your fenced code block has any params, e.g. a lang param.

**Comment by mootari** [comment]
> Please note that the langPrefix workaround only works if your fenced code block has any params, e.g. a lang param.

I've posted a small plugin to set a default language in https://github.com/jonschlinkert/remarkable/issues/131#issuecomment-357460641.
