### ISSUE TITLE
Spell Check feature

### ISSUE THREAD

**Issue by marc0der** [jonschlinkert/remarkable#232]
I'm really enjoying using Remarkable, so firstly, thanks for the fantastic editor!

It would be very useful if Remarkable plugged into some spell-checking library. It would be nice to have a similar experience to when you are typing in a browser with red underlined squiggly beneath misspelled words.

I'm no python expert, otherwise I would have a try at implementing it myself. Thanks for the great work and keep up the effort!

**Comment by doowb** [comment]
@marc0der this repository is for the markdown parser. I think you're looking for the Remarkable editor (which I don't have a link).

**Comment by marc0der** [comment]
Sorry and thanks!

**Comment by vyp** [comment]
@marc0der https://github.com/jamiemcg/Remarkable

**Comment by marc0der** [comment]
Thanks, already got it.
