### ISSUE TITLE
Live preview eats CPU when typing fast -> add a delay ?

### ISSUE THREAD

**Issue by mdouchin** [jonschlinkert/remarkable#239]
When using the live preview feature, Remarkable eats CPU when typing fast. It is noticeable, because it slows down the writing of the characters in the left panel (raw text). Sometimes, it even prevents me from typing.

I think an easy solution could be to wait for N chars typed, or for N seconds before refreshing the live preview. "Live" does not need to be "microseconds live". I am confident many users would find it acceptable if "live" meant "Every N seconds".

Havind an option to set this N could be good too.

**Comment by doowb** [comment]
@mdouchin I think you're looking for the Remarkable editor found here: https://github.com/jamiemcg/Remarkable

If you're referring to the Live Demo web page, feel free to reopen this issue.

**Comment by mdouchin** [comment]
oups, sorry :(
