### ISSUE TITLE
Cannot change syntax highlighting of the editable area under Ubuntu 16.04

### ISSUE THREAD

**Issue by RobertoPrevato** [jonschlinkert/remarkable#243]
Styles seem to not be applied on the editor panel, under Ubuntu 16.04. The background of the editable area is always gray and some elements are really hard to read (e.g. texts inside square brackets). Switching the night mode on/off, doesn't produce any result on the interface. I have Unity Tweak tool installed and I am using a custom theme (Arc), but this doesn't seem to be the cause because the same issue persists when using default Ubuntu themes (for example, Ambiance).

If possible, could you please indicate a configuration file that can be edited to change the colors of the editable area?

![screenshot from 2016-10-25 22-05-26](https://cloud.githubusercontent.com/assets/2576032/19702414/d48611e8-9aff-11e6-9c78-0c102c819fe2.png)

**Comment by DiscoNova** [comment]
This repository is for Remarkable, the markdown parser library ... not Remarkable, the editor ... You're looking for https://github.com/jamiemcg/remarkable ;)

**Comment by RobertoPrevato** [comment]
Sorry for the mistake!
