### ISSUE TITLE
Unordered sub-lists do not work within unordered lists when using Github syntax

### ISSUE THREAD

**Issue by tscott0** [jonschlinkert/remarkable#251]
The below example does not appear indented in the preview pane.
```
* item 1
* item 2
  * item should be indented
* item 3
```

It should look like this:
* item 1
* item 2
  * item should be indented
* item 3

**Comment by doowb** [comment]
It looks like it's working in the [demo here](https://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiolMjBpdGVtJTIwMSU1Q24qJTIwaXRlbSUyMDIlNUNuJTIwJTIwKiUyMGl0ZW0lMjBzaG91bGQlMjBiZSUyMGluZGVudGVkJTVDbiolMjBpdGVtJTIwMyUyMiwlMjJkZWZhdWx0cyUyMjolN0IlMjJodG1sJTIyOmZhbHNlLCUyMnhodG1sT3V0JTIyOmZhbHNlLCUyMmJyZWFrcyUyMjpmYWxzZSwlMjJsYW5nUHJlZml4JTIyOiUyMmxhbmd1YWdlLSUyMiwlMjJsaW5raWZ5JTIyOnRydWUsJTIybGlua1RhcmdldCUyMjolMjIlMjIsJTIydHlwb2dyYXBoZXIlMjI6dHJ1ZSwlMjJfaGlnaGxpZ2h0JTIyOnRydWUsJTIyX3N0cmljdCUyMjpmYWxzZSwlMjJfdmlldyUyMjolMjJodG1sJTIyJTdEJTdE)

If this is related to the Remarkable text editor, this is the wrong repository. Try this one: https://github.com/jamiemcg/remarkable
