### ISSUE TITLE
Crashes if you say before new window is opened

### ISSUE THREAD

**Issue by nuocu** [jonschlinkert/remarkable#252]
If you click on File->New and then on File->Save before the new window with the blank document is open, the old window will crash and close - without saving. 

I can reproduce this. I use arch linux and the version from the repo (1.87).

**Comment by jonschlinkert** [comment]
Wrong project. are you looking for https://github.com/jamiemcg/Remarkable?

**Comment by nuocu** [comment]
I am and I am sorry.

**Comment by jonschlinkert** [comment]
oh no worries, it happens :)
