### ISSUE TITLE
Using remarkable as jekyll markdown processor

### ISSUE THREAD

**Issue by OmarSquircleArt** [jonschlinkert/remarkable#255]
Hello

I am creating a blog using jekyll, and it is using **kramdown** by default but I don't like it and I want to use remarkable.

Is there anyway we would be able to use remarkable as our markdown processor?

**Comment by jonschlinkert** [comment]
For jekyll? Hmm, not that I know of, but I don't claim to be an expert on Jekyll. You could always try a different static site generator. 

Closing since this might be a better question to ask Jekyll.  Thanks for the comment though, let me know if you find anything out.

**Comment by OmarSquircleArt** [comment]
It was mentioned in the [documentation](https://jekyllrb.com/docs/configuration/#custom-markdown-processors) that we can add a custom markdown processor. But this assuming the parser is a ruby gem, and since remarkable is a Js thing we can't.
Thanks anyway, and thanks for your awesome work.

**Comment by jonschlinkert** [comment]
bummer, good to know. and thank you for trying!
