### ISSUE TITLE
How can I write to-do list?

### ISSUE THREAD

**Issue by huyvohcmc** [jonschlinkert/remarkable#256]
Am I wrong or Remarkable just doesn't support to-do list at the moment?

![image](https://cloud.githubusercontent.com/assets/17645203/22875801/3225349e-f200-11e6-9615-0f67f02c7aa2.png)

**Comment by jonschlinkert** [comment]
> Am I wrong

Well, wrong repository lol. I think you're looking for https://github.com/jamiemcg/Remarkable

**Comment by huyvohcmc** [comment]
Lol wut sorry man...
