### ISSUE TITLE
 How does toc and markdown work together?

### ISSUE THREAD

**Issue by softdev-zeus** [jonschlinkert/remarkable#257]
Thank you for your remarkable and markdown-toc.
I have rendered markdown and generated toc from it.
But I don't know how to link two things together?
I would appreciate if you post any sample code.

**Comment by jonschlinkert** [comment]
On the [markdown-toc readme](https://github.com/jonschlinkert/markdown-toc#tocplugin)

**Comment by softdev-zeus** [comment]
Oh sorry, I didn't have mentioned in detail.
I have generated toc and rendered markdown on page.
I made sure that toc has accurate links to heading of markdown, but there aren't attached ids in rendered markdown.
I would like to know how to link to heading of rendered markdown when I click on toc.
Are there any methods in markdown-toc or remarkable?
![screenshot_1](https://cloud.githubusercontent.com/assets/24817343/22991434/0f85d6ce-f371-11e6-8010-17b4b570728b.png)

**Comment by jonschlinkert** [comment]
> I would like to know how to link to heading of rendered markdown when I click on toc.

Oh I see. Thanks for the additional detail. I [posted an example](https://github.com/jonschlinkert/remarkable/issues/250#issuecomment-271180226) of how to modify HTML in another issue. That same approach should work for this. Hope that helps
