### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by john-cj** [jonschlinkert/remarkable#259]
I don't know is it OK to post such ideas here, but it would be very cool for me (and, I believe, for many another users) to have Remarkable Chrome extension.

Yesterday I installed and checked all 22 markdown viewers from Chrome Web Store, and all of them, except one, are based on Marked and Showdown parsers. And the only another extension is based on Commonmark.js parser. So, I doesn't found any extension based Remarkable.

Also, this would be great in the sense of promotional activity for this project.

Personally, I'm interested in ***reader***, not ***side-by-side editor*** extension. Something like
https://chrome.google.com/webstore/detail/markview/iaddkimmopgchbbnmfmdcophmlnghkim
but based on Remarkable would be super useful.

**Comment by jonschlinkert** [comment]
wrong library

**Comment by tunnckoCore** [comment]
@jonschlinkert why not? hm.

**Comment by jonschlinkert** [comment]
Oh sorry lol, sounded like they meant https://github.com/jamiemcg/Remarkable.

**Comment by tunnckoCore** [comment]
haha, good point. i just noticed that you closed recently few issues (in other projects) with that response, so i thought, let's ask for that specific case.

**Comment by johncja** [comment]
@jonschlinkert Glad to see it is reopened :-)
