### ISSUE TITLE
tables: text is not centered inside tables

### ISSUE THREAD

**Issue by stavpup** [jonschlinkert/remarkable#262]
Example;

| Left | Center | Right |
| --- | :---: | ---: |
| a | a | a |
| bb | bb | bb |
| cccc | ccc | ccc |

text is not centered inside tables

![001](https://cloud.githubusercontent.com/assets/10577035/24330646/e5a10688-122b-11e7-9810-875982059c9e.png)

**Comment by doowb** [comment]
@stavpup I think you're looking for the [Remarkable editor](https://github.com/jamiemcg/remarkable). This is the remarkable markdown parser.
