### ISSUE TITLE
I have some pending text, but that is exactly the text which suppose to start my inline token

### ISSUE THREAD

**Issue by elisei-timofte** [jonschlinkert/remarkable#266]
Hi,

I'm writing two parsing rules one for capturing `@name` and another one to capture `#hashtag`.
For both of them the state.pos is 5. Why is that, and how can I fix it to start from 0, so it will match my '#'. 

I don't know why for the '@' it works perfectly, but it doesn't capture none of the hashtags. The only difference in the rules is the starting point.

Here are some screenshots to see the state for both rules:

<img width="784" alt="screen shot 2017-04-25 at 09 50 27" src="https://cloud.githubusercontent.com/assets/6162068/25372132/c17fd42c-299c-11e7-9f93-9ad3c50cc575.png">
<img width="828" alt="screen shot 2017-04-25 at 09 51 02" src="https://cloud.githubusercontent.com/assets/6162068/25372133/c1830976-299c-11e7-8b91-ba0cc755c4b6.png">

Here is the code:

``` coffee
parsing_rules.alias = (state, silent) ->
  found    = false
  pos      = 0
  stack    = 0
  max      = state.posMax
  start    = state.pos
  lastChar = ''
  nextChar = ''

  if state.src.charAt(start) != '@'
    return false
  if silent
    return false # don't run any pairs in validation mode

  lastChar = if start > 0 then state.src.charAt(start - 1) else -1
  nextChar = state.src.charAt(start + 1)
  if lastChar != -1 and lastChar != ' '
    return false
  if nextChar == ' ' or nextChar == '\n'
    return false

  state.pos = start
  stack = 1
  while state.pos++ <= max
    if state.src.charAt(state.pos) == ' ' or state.src.charAt(state.pos) == '\n' or (state.pos) == max
      lastChar = state.src.charAt(state.pos - 1)
      nextChar = if state.pos + 1 < max then state.src.charAt(state.pos + 1) else -1
      if lastChar != ' '
        # closing 'custom_alias'
        stack--
      else if nextChar != ' ' and nextChar != '\n'
        # opening 'custom_alias'
        stack++

      if stack <= 0
        found = true
        break

  if !found
    # parser failed to find ending tag, so it's not valid alias
    state.pos = start
    return false

  # found!
  state.posMax = state.pos
  state.pos = start + 1
  if !silent
    # readd the replaced space
    # if state.src.charAt(state.posMax) == ' '
    #   state.src = state.src.slice(0, state.posMax) + ' ' + state.src.slice(state.posMax)
    state.push
      type: 'custom_alias_open'
      level: state.level++
    state.parser.tokenize state
    state.push
      type: 'custom_alias_close'
      level: --state.level
  state.pos = state.posMax + 1
  state.posMax = max
  true
```

Here is how the parsing rules are used among the rendering rules:

``` coffee
# get the remarkable default rules
rendering_rules = require 'remarkable/lib/rules'
parsing_rules   = require './parsing_rules.coffee'

# add some in-house tag related rules
rendering_rules.custom_alias_open = (tokens, idx, options, env) ->
  return "<span class='tags-tag__button tags-tag__button--text-format tags-tag__button-person'>@"

rendering_rules.custom_alias_close = (tokens, idx, options, env) ->
  return ' </span>'

rendering_rules.custom_hashtag_open = (tokens, idx, options, env) ->
  return "<span class='tags-tag__button tags-tag__button--text-format tags-tag__button-hashtag'>#"

rendering_rules.custom_hashtag_close = (tokens, idx, options, env) ->
  return ' </span>'

module.exports = (md, options) ->
  opts = _.extend {}, options
  md.inline.ruler.push 'custom_alias', parsing_rules.alias
  md.inline.ruler.push 'custom_hashtag', parsing_rules.hashtag
  md.renderer.rules = rendering_rules
```

**Comment by elisei-timofte** [comment]
I've found a workaround. Maybe is not the best, so if someone has a better solution I'm opened

I discovered what does the pending means in the next screenshot

<img width="189" alt="screen shot 2017-04-25 at 13 39 13" src="https://cloud.githubusercontent.com/assets/6162068/25381482/9c649fea-29bc-11e7-8b35-a3539af68bc0.png">

`#type` from `pending: '#type'` is treated as pure text (containing no special chars from the markdown markup).

My solution was to duplicate the [text.js](https://github.com/jonschlinkert/remarkable/blob/43eaf67dd3bb4a850542ad868b59fe75409a17a7/lib/rules_inline/text.js) file in my project and to add also my special char `#`.

Ending up with this code

```
rendering_rules            = require './rendering_rules.coffee'
parsing_rules              = require './parsing_rules.coffee'
modified_text_parsing_rule = require './modified_text_parsing_rule.coffee'

module.exports = (md, options) ->
  opts = _.extend {}, options
  md.inline.ruler.push 'custom_person', parsing_rules.person
  md.inline.ruler.push 'custom_hashtag', parsing_rules.hashtag

  # see the DISCLAIMER in the required file
  md.inline.ruler.at 'text', modified_text_parsing_rule

  md.renderer.rules = rendering_rules
```

Note the line `md.inline.ruler.at 'text', modified_text_parsing_rule` where I've replaced the old markdown text rule with mine.

Waiting feedback. Thanks

**Comment by doowb** [comment]
@elisei-timofte I'm doing something similar in [remarkable-mentions](https://github.com/doowb/remarkable-mentions/blob/master/index.js#L25). I'm adding the rule after the core `block` rule. This ensures that it will run before other rules like `inline`. Since it will capture the `@` before the `text` rule is run, then you shouldn't have to override it.

Hope this helps.

**Comment by elisei-timofte** [comment]
I'll try. Thanks for the hint.

Also wondering if there is a way to enable emphasis in code block?
