### ISSUE TITLE
In a list , after a code block , the next line can not be aligned correctly

### ISSUE THREAD

**Issue by an15m** [jonschlinkert/remarkable#267]
Find it in using atom plugin `markdown-preview-enhanced`

![1](https://cloud.githubusercontent.com/assets/8855703/25366181/8faf8bb4-29a0-11e7-8f6e-57130e3ef6ba.png)
![2](https://cloud.githubusercontent.com/assets/8855703/25366180/8fa3b4c4-29a0-11e7-8770-1a8f94ca4b1e.png)

**Comment by doowb** [comment]
@an15m I think you're looking for the [Remarkable editor](https://github.com/jamiemcg/remarkable).

If this is an issue with this remarkable markdown parser, then please show an example of the code that you are using to reproduce the issue.

**Comment by an15m** [comment]
It has no problem in Remarkable editor . So sorry , you can close it . May be something wrong with the `markdown-preview-enhanced`

**Comment by an15m** [comment]
Sorry to bother again， I want to know whether the Remarkable editor using this remarkable markdown parser ? Remarkable edit has no problem . But markdown-preview-enhanced has , the author of it say it using this remarkable markdown parser . Thx~

**Comment by doowb** [comment]
I understand now. I didn't know exactly where the screenshots came from. I see now that one is the raw markdown file and the other is the markdown rendered through `markdown-preview-enchanced`

This markdown parser follows the `commonmark` spec and what you are seeing is correct for a list item. You can read more about the list item [spec here](http://spec.commonmark.org/0.27/#list-items).

To get the correct indentation, you should indent the paragraph below the code block to line up with the first paragraph:

````
* haha
    ```
    test
    ```
  test
````

I hope this helps.

**Comment by jonschlinkert** [comment]
closing based on @doowb's last response. Please feel free to re-open if you have more questions, or ask on stackoverflow and link back here. thanks
