### ISSUE TITLE
Fix HTML preview scroll reset.

### ISSUE THREAD

**Issue by artefom** [jonschlinkert/remarkable#272]
This happens when editing markdown and viewing preview that is too big to fit entirely into screen, thus scrolled down to view place where things are edited. You press enter and whoops - you preview scroll is reset and you can view only top of document until you scroll the code part again. This happens in Ubuntu 16.04.

**Comment by jonschlinkert** [comment]
Were you looking for [Remarkable Editor](https://remarkableapp.github.io/)?

**Comment by erm3nda** [comment]
This reply link should point to https://github.com/jamiemcg/remarkable.
