### ISSUE TITLE
[Feature Request] Ability to stay at bottom of document

### ISSUE THREAD

**Issue by Helithumper** [jonschlinkert/remarkable#285]
I am in class writing notes in markdown and whenever I type the document scrolls back to the top. A toggle to stay at the bottom of the document would be EXTREMELY handy :)

**Comment by DiscoNova** [comment]
I am guessing you're currently in the wrong "Remarkable" ... this one is "only" a parser ... https://github.com/jamiemcg/Remarkable is an editor. The parser does not "scroll" at all ;)

**Comment by doowb** [comment]
Thanks @DiscoNova

**Comment by networkimprov** [comment]
If you added a new-issue template that points to the other Remarkable, you might see less of these :-)
