### ISSUE TITLE
Is browser build size significant?

### ISSUE THREAD

**Issue by puzrin** [jonschlinkert/remarkable#29]
Current size is 24K gzipped. If it's critical - it's possible to reduce (code for node and browser will be different):
1. Decode named entities via textarea -> 16K gzipped
2. + Remove autolinker or make it more stupid (simple regex) -> 12.3K gzipped

Entity decode for browser:

``` js
var ta;

function decodeEntities(input) {
  ta = ta || document.createElement('textarea');
  ta.innerHTML = input;
  return y.value;
}
```

Thechnically - move decode fn to separate file & define replacement rule for `browserify`

**Comment by TrySound** [comment]
Linkify is moved to own entry point as plugin. Gonna provide browser build with textarea trick. Thanks for the idea!

**Comment by TrySound** [comment]
I used the trick in the topic and reduced browser bundle from 25446 to 13775 gzipped 🎉 
https://github.com/jonschlinkert/remarkable/pull/359
