### ISSUE TITLE
...

### ISSUE THREAD

**Issue by anselmbradford** [jonschlinkert/remarkable#301]
`underscore.string` has a [Regular Expression Denial of Service vulnerability](https://snyk.io/vuln/npm:underscore.string:20170908) introduced into `remarkable` through `argparse@0.1.16`. It appears `argparse` could be updated to version `1.0.10` to fix this.

**Comment by jonschlinkert** [comment]
please [don't create security vulnerability issues](https://en.wikipedia.org/wiki/Responsible_disclosure) .

**Comment by anselmbradford** [comment]
This issue is [already published](https://snyk.io/test/npm/remarkable). 
Do you have a rough timeline for the next release?
