### ISSUE TITLE
Is `breaks: true` broken?

### ISSUE THREAD

**Issue by shockey** [jonschlinkert/remarkable#308]
I have `breaks: true` set, but I can't get any newline-to-break behavior to happen. 

Example: [Remarkable demo link](http://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiMlMjBSZW1hcmthYmxlJTVDbiU1Q25TaG91bGRuJ3QlMjB0aGlzJTVDJTVDbiUyMHBhcmFncmFwaCUyMGJlJTIwb24lMjB0d28lMjBsaW5lcz8lNUNuJTVDbldoYXQlMjBhYm91dCUyMHRoaXMlNUMlNUNuJTVDJTVDbiUyMG9uZT8lNUNuJTVDbkZyb20lMjBsb29raW5nJTIwYXQlMjB0aGUlMjBkZWJ1Z2dlciwlMjBpdCUyMGFwcGVhcnMlMjB0aGF0JTIwdGhlJTIwJTYwJTVDJTVDbiU2MCUyMGlzJTIwYmVpbmclMjBlc2NhcGVkOiU1Q24lNUNuJTYwJTYwJTYwJTVDbiUyMCUyMCUyMCUyMCU1QyUyMnR5cGUlNUMlMjI6JTIwJTVDJTIyaW5saW5lJTVDJTIyLCU1Q24lMjAlMjAlMjAlMjAlNUMlMjJjb250ZW50JTVDJTIyOiUyMCU1QyUyMlNob3VsZG4ndCUyMHRoaXMlNUMlNUMlNUMlNUNuJTIwcGFyYWdyYXBoJTIwYmUlMjBvbiUyMHR3byUyMGxpbmVzPyU1QyUyMiwlNUNuJTIwJTIwJTIwJTIwJTVDJTIybGV2ZWwlNUMlMjI6JTIwMSwlNUNuJTYwJTYwJTYwJTIyLCUyMmRlZmF1bHRzJTIyOiU3QiUyMmh0bWwlMjI6ZmFsc2UsJTIyeGh0bWxPdXQlMjI6ZmFsc2UsJTIyYnJlYWtzJTIyOnRydWUsJTIybGFuZ1ByZWZpeCUyMjolMjJsYW5ndWFnZS0lMjIsJTIybGlua2lmeSUyMjp0cnVlLCUyMmxpbmtUYXJnZXQlMjI6JTIyJTIyLCUyMnR5cG9ncmFwaGVyJTIyOnRydWUsJTIyX2hpZ2hsaWdodCUyMjp0cnVlLCUyMl9zdHJpY3QlMjI6ZmFsc2UsJTIyX3ZpZXclMjI6JTIyaHRtbCUyMiU3RCU3RA==)

Am I missing something here?

CC: https://github.com/swagger-api/swagger-ui/issues/3867

**Comment by doowb** [comment]
In the demo example, you're mentioning that the `\n` is being escaped, which is true because that's from the text editor used in the demo page. If you put actual newlines into the editor by pressing "enter", then you'll see in the `html` view there are `<br>` tags.

The `swagger-ui` issue you referenced looks like it's more about a spacing issue with styles and not the html being created from markdown.

**Comment by TrySound** [comment]
@shockey Is this still a problem?

**Comment by brandonburr** [comment]
@TrySound afaik this is still a problem. I can't get <br> tags to show up at all. 

See Remarkable Demo page with 'breaks:true' on, and putting newlines into the editor via 'enter' as @doowb suggests.

Example: [https://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiMlMjBSZW1hcmthYmxlJTVDbiU1Q25CcmVha3MlMjBubyUyMGxvbmdlciUyMHdvcmtzPyU1Q24lNUNuJTVDbiU1Q24lNUNuJTVDblRoZXJlJTIwc2hvdWxkJTIwYmUlMjA0JTIwJTNDYnIlM0UlMjBiZXR3ZWVuJTIwdGhlc2UlMjBsaW5lcy4lNUNuJTVDbiU1Q24lNUNuSG93ZXZlciUyMHRoZXJlJTIwYXJlJTIwbm9uZS4lMjBXaGF0JTIwYW0lMjBJJTIwZG9pbmclMjB3cm9uZz8lMjIsJTIyZGVmYXVsdHMlMjI6JTdCJTIyaHRtbCUyMjpmYWxzZSwlMjJ4aHRtbE91dCUyMjpmYWxzZSwlMjJicmVha3MlMjI6dHJ1ZSwlMjJsYW5nUHJlZml4JTIyOiUyMmxhbmd1YWdlLSUyMiwlMjJsaW5raWZ5JTIyOmZhbHNlLCUyMmxpbmtUYXJnZXQlMjI6JTIyJTIyLCUyMnR5cG9ncmFwaGVyJTIyOmZhbHNlLCUyMl9oaWdobGlnaHQlMjI6ZmFsc2UsJTIyX3N0cmljdCUyMjpmYWxzZSwlMjJfdmlldyUyMjolMjJodG1sJTIyJTdEJTdE](url)

**Comment by doowb** [comment]
When I hit <kbd>enter</kbd> inside a paragraph, it adds a `<br>`. But if I hit <kbd>enter</kbd> again, then it creates a new `<p>` tag in the html. I think this is correct behavior, but I haven't looked at the spec to see if this is specified or not.

**Comment by brandonburr** [comment]
Do you see `<br>`s in the example I linked? Am I misunderstanding? I assumed there should be 4 `<br>`s between the top two lines, and this is what I see: ![image](https://user-images.githubusercontent.com/1245838/66152067-7aa1ef00-e5cd-11e9-91e7-815179faed62.png)`

**Comment by doowb** [comment]
I think this is correct and if you really want to add additional lines of space, you can set `html: true` and add `<br>` tags.

For what it's worth... this text field I'm typing in now that uses GFM handles the newlines in paragraphs the same way as `remarkable` with `breaks: true`.

**Comment by brandonburr** [comment]
fair enough. ok thanks for the explanation!

**Comment by doowb** [comment]
Np, I hope you get it working the way you want it to. I double checked the original issue from swagger-ui and they also fixed their issue (it wasn't due to `remarkable`).
