### ISSUE TITLE
security vulnerability with using old version of underscore.string

### ISSUE THREAD

**Issue by shiup** [jonschlinkert/remarkable#310]
✗ High severity vulnerability found on underscore.string@2.4.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:underscore.string:20170908

**Comment by robotsrule** [comment]
I ran into this using Snyk this week as well.  I submitted a PR to update the package.json to use a non vulnerable version of argparse.

https://github.com/jonschlinkert/remarkable/pull/312

**Comment by janotav** [comment]
We are affected by this issue as well - remarkable being dependency of grafana. Any chances of getting this merged & released in foreseeable future?

**Comment by shockey** [comment]
Chiming in from downstream - this is a concern for us over at Swagger UI as well (cc https://github.com/swagger-api/swagger-ui/issues/5152)

**Comment by opatut** [comment]
The `underscore.string` dependency comes from `argparse < 1.0.0`, so `argparse` version needs to be upgraded. In 1.0.0 argparse switched to lodash and doesn't have this problem anymore. There seems to be [no breaking changes](https://github.com/nodeca/argparse/blob/master/CHANGELOG.md) for that argparse upgrade.

**Comment by uiteoi** [comment]
@opatut could you do a pull request to upgrade argparse to 1.0.0?

**Comment by opatut** [comment]
There you go ;)

**Comment by opatut** [comment]
Haha I just realized there are now [4 differnent PRs](https://github.com/jonschlinkert/remarkable/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+argparse) for that. One of them also fixed all the travis testing hikkup, so you might want to merge that one (#323) and get this thing green again.

**Comment by plroebuck** [comment]
When should we expect an updated release for this?

**Comment by prabuvenkat** [comment]
When can we expect an update release for this ?
