### ISSUE TITLE
Clarify CommonMark support

### ISSUE THREAD

**Issue by acdha** [jonschlinkert/remarkable#316]
The project page and README don't make it immediately obvious that the only dialect supported is CommonMark, rather than that being something you could opt into with the `commonmark` preset. I'm assuming there is no intention to support anything else so perhaps things like “Markdown parser, done right. Commonmark support, extensions, syntax plugins, high speed - all in one.” should be “CommonMark parser, done right. Extensions, syntax plugins, high speed - all in one. ”, etc.

**Comment by jonschlinkert** [comment]
I'm not sure what you mean. What other dialects are not possible with Remarkable? 

Closing since plugins can be used to add support for any dialect you can think of.
