### ISSUE TITLE
Load external Markdown File in html.

### ISSUE THREAD

**Issue by MaxWhite20062003** [jonschlinkert/remarkable#330]
Well, I think the title is self explanatory ^^\

I have a Markdown File named "article.md", and want use this file inside of my html.
```markdown
# Hello World!
Lorem Ipsum
- Lorem Ipsum
```
```html
<h1>Hello World!</h1>
<p>Lorem Ipsum</p>
<ul>
    <li>Lorem Ipsum</li>
</ul>
````

**Comment by TrySound** [comment]
You may use fetch https://github.com/github/fetch and pass it into remarkable after. Then you may apply result with innerHTML.
