### ISSUE TITLE
ProjectFolder | MultiTab

### ISSUE THREAD

**Issue by stoffel2107** [jonschlinkert/remarkable#336]
I've been using remarkable for a few projects and like the feel of it.

What I'm missing is, is that I sometimes want to open a project folder with multiple markdown files to work on(e.g. git Wikis) therefore it would be nice, if remarkable supports either project folders or something like a Multi Tab window, or both.

**Comment by DiscoNova** [comment]
Wrong remarkable? You're probably looking for the editor ;) https://github.com/jamiemcg/remarkable

**Comment by stoffel2107** [comment]
xDD it does seem like i have the wrong project doesn't it. sry
