### ISSUE TITLE
Broken test script

### ISSUE THREAD

**Issue by claudiopro** [jonschlinkert/remarkable#339]
The `test` script is failing with an error:

```
→ yarn test
Using globally installed version of Yarn
yarn run v1.12.1
$ make test
make: eslint: No such file or directory
make: *** [lint] Error 1
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

Reproduced locally on my laptop:
- Node v10.14.2
- Yarn v1.12.1

and on Travis CI:
https://travis-ci.org/jonschlinkert/remarkable/builds/532298303?utm_source=github_status&utm_medium=notification

**Comment by shockey** [comment]
Looks like some recent commits by @TrySound have resolved this -- can you try again on your local @claudiopro?
