### ISSUE TITLE
Feature request: Add index panel

### ISSUE THREAD

**Issue by jm4R** [jonschlinkert/remarkable#342]
I think it would be nice to have index panel with a list of paragraphs (like Table of Contents). It would help editing big documents.

**Comment by DiscoNova** [comment]
I believe you're looking for https://github.com/jamiemcg/Remarkable ... which is the editor, "Remarkable with a capital R" ... this project is for a parser, "remarkable with a lower-case r" :) ... haven't seen editor feature requests here for a couple weeks now - but it happens pretty constantly ;)

**Comment by jm4R** [comment]
I see. Thanks and sorry for mistake :)
