### ISSUE TITLE
[Meta] v1.7.2 & v1.7.3

### ISSUE THREAD

**Issue by shockey** [jonschlinkert/remarkable#357]
How was the content for v1.7.2 and v1.7.3 selected, and where is development of that line being tracked?

It doesn't include #349, and I can't find a branch that indicates a version higher than v1.7.0.

**Comment by shockey** [comment]
cc @TrySound

**Comment by TrySound** [comment]
I cherry-picked two asked fixes here
https://github.com/jonschlinkert/remarkable/commits/v1.x

**Comment by bashofmann** [comment]
Would it be possible to cherry-pick #349 and get a release with this as well?

**Comment by TrySound** [comment]
Upgraded without test as fast fix. Published 1.7.4.

**Comment by shockey** [comment]
thanks @TrySound!
