### ISSUE TITLE
JSX

### ISSUE THREAD

**Issue by sdegutis** [jonschlinkert/remarkable#361]
Hi. I've been evaluating different JS-based Markdown parsers for use in a client project I have which would benefit from a Markdown parser that understands JSX code, including the ability to contain arbitrary JavaScript within attributes (such as arrow-functions within onClick handlers). The goal is to have Markdown that can be compiled into raw React-friendly JSX code.

For example, this would be allowed:

```markdown
# This is a <span onClick={(e) => doStuff(e.target.innerText.toUpperCase())}>header</span>

<div className='something'>

This *should* be within a paragraph tag.

- And this is a list:
  - <Foo/>
  - <Bar/>
  - <Qux/>

</div>
```

(I'm not sure on the specifics of proper indentation within the div, that's one of my weakest points of understanding about the intricacies of Markdown syntax, so please ignore that aspect of my example.)

The library you maintain ticked every box for a JS-based Markdown compiler for my use-case, but especially the ease and flexibility of extending the language's syntax. (I should also add that it's some of the best code I've ever seen in my career, kudos to @puzrin and @rlidwka et al.)

After reading your plugin guides, I think I have an idea of how this can be implemented as a `remarkable` extension. This issue is partly to get feedback and general guidance on my implementation idea, and partly to suggest that this feature might be universally useful enough to merit becoming a core part of the language, implemented as built-in rules, and enabled by a configuration option.

The goal is to be able to transform these:

```jsx
// simple tranformation:
<div>*foo*</div>
<div><em>foo</em></div>

// more complex transformation:
<List render={items.map(item => <>*foo {item}*</>)}/>
<List render={items.map(item => <><em>foo {item}</em></>)}/>
```

The current `htmltag` rule's default parsing implementation, as far as I can tell, starts parsing when it hits `<`, parses it as either an opening or closing tag, and returns control back to the parser when the tag is done. Because both opening and closing tags start with `<`, it can use the same parse logic when hitting both, so it doesn't need to do anything special for the inner text. In other words, each opening and closing tag are self-sufficient and considered independent from one another.

But this strategy won't work with JSX. In the list-render section above, consider that it could be split into these semantically distinct parts:

- `<List render={items.map(item => <>` (the first JSX portion, should be emitted as-is)
- `*foo ` (the first plain text portion, should be rendered as Markdown, starting the process of an emph token)
- `{item}` (the second JSX portion, should also be emitted as-is)
- `*` (the second plain text portion, should close and emit the emph token)
- `</>)}/>` (the final JSX portion, should be emitted as-is)

I found a way to use `require('@babel/parse').parseExpression(...)` to get the end of the current JSX expression and all text nodes within it, in a way that can be represented like this:

```typescript
interface ParseResult {
  endPos: number;
  innerTextNodes: Array<{
    startPos: number;
    endPos: number;
    text: string;
  }>;
}
```

At first I was thinking of just calling the top-level `md.renderInline(textNode)` on each inner text node (called JSXText in Babel's parser terms) using the visitor pattern via a Babel plugin to get to them. But in this example, it wouldn't know that the fourth node containing `*` is the closing emphasis-tag for the one started in the second node containing `*foo `.

Then I figured out that inline parsers have the ability to call `state.parser.tokenize(state)` to continue parsing with the current context. Using this function, the main issue to be solved now is that the parser doesn't have the same "idempotent" way of knowing that parsing our JSX needs to be resumed. For instance, the third node in the above example starts with `{`, not `<`.

So my implementation idea involves two phases, represented by two different rules.

The first replaces `htmltag` via `md.inline.rules.at`, and is responsible for recognizing the JSX expression at `<`, storing the `ParseResult` information internally, consuming and emitting the JSX literally as a token, and giving control back to the parser via `state.parser.tokenize(state)`.

The second tag would be responsible for knowing when the state enters back into the JSX expression parsing phase. It would do this by looking at the current parser's *position*, and comparing it to the `ParseResult` expression stored from the first rule, and would return true IFF the parser's position is at the exact end of any inner text nodes.

The reason for having two rules is because the `htmltag` rule has lower precedence and may not be able to catch all characters that could possibly trigger the end of a JSXText node, thus the second rule should have higher precedence, possibly even above 'text'.

Alternatively, maybe the `htmltag` rule could just be moved higher in precedence and contain both responsibilities, but then it would have to make sure it's not inside of an illogical context, e.g. inside of the URL portion of a link where JSX isn't allowed but where `<` (theoretically) might be. This example may not be perfect but it illustrates the reason I'm thinking precedence might matter.

Also, it *seems* that the only two things that can end a text node is `{` and `<`, and that the only character that can start a new overall JSX expression is `<`, but I haven't thought of enough examples that might disprove these two assumptions. If they can be (at least reasonably) proven to be true, it would make figuring out this precedence issue a lot easier.

This is my plan, and all my notes and thoughts on its implementation. If anyone is interested in solving the same problem with me, I'd love to hear your feedback and thoughts on it. In the meantime, I'm going to work on the implementation and continue to post any relevant notes in here related to my progress on this.

**Comment by sdegutis** [comment]
I forgot to touch on the topic of the `htmlblock` implementation in that first comment. Oops. I'm reading the block-based parsing docs now, will add some implementation thoughts in a bit.

Also, the docs mention `state.level`, and the concept of levels and nesting sound exactly perfect for the JSXText node processing. But looking through the source of built-in rules, it looks like this is merely a bit of state given to the renderer and only used for determining how to render, not actually being an ability to recurse into and out of nested parsing.

**Comment by DiscoNova** [comment]
Problem with JSX is that it is little more than some syntactic sugar over "plain JavaScript content". The result of JSX markup (with some properties etc.) could, if I'm not mistaken, rather easily be fed to Remarkable's `render()` but ... other than that (i.e. result of server-side rendering of JSX) I fail to see any real benefit?

Perhaps I'm missing something?

**Comment by sdegutis** [comment]
@DiscoNova Several unrelated organizations and individuals are showing a lot of interest in the concept of "JSX in Markdown" and are converging mostly through the [MDX](https://mdxjs.com) project. My particular client project's needs diverge from the implementation that MDX chose, but the exact same concept is still very relevant to me, hence my interest in implementing this as a `remarkable` plugin. You're right that rendering it is probably exactly the same as the current renderer functions for `htmltag` and `htmlblock`, that is, it would just emit it as-is. The difficulty is in parsing it correctly while keeping track of current parser state, given that JSX can contain nested Markdown which can contain nested JSX, etc. ad inf.

**Comment by sdegutis** [comment]
Here are some situations which I *think* belong to the processing of JSX blocks (via an overridden `htmlblock` rule probably):

```jsx
<Foo>Single line block *with inline Markdown*</Foo>

---

<Foo>
  <Bar>
    This should *not* render as a paragraph since it's not surrounded by blank lines.
  </Bar>
</Foo>

---

<Foo>
  <Bar>

This *should* render as a paragraph since it *is* surrounded by blank lines.

  </Bar>
</Foo>

---

<Foo
  render1={<>Multi-line block that recursively contains *inline Markdown*</>}
  render2={<>

But it can *also* have block-level Markdown content if surrounded by blank linkes.

(After this line, the following two non-blank linkes) should be parsed as JSX somehow.

  </>}
  />
```

**Comment by sdegutis** [comment]
I started to think maybe we don't have to parse JSX blocks separately than inline JSX, simplifying everything to one rule. But, assuming my understanding of `remarkable` parsing is correct, the main benefit of having JSX blocks be different than HTML tags is to avoid extraneous `<p>` tags, because e.g. all the block examples in my last comment might want to render their own `<div>` elements or something, and might not expect to be rendered inside a `<p>`. Which means we probably do need to implement block-based JSX parsing.

**Comment by sdegutis** [comment]
The current `htmlblock` rule starts by finding a line that starts with `<`, and continues to parse every line until it finds a blank line. This strategy won't work for JSX expressions, because they can contain JavaScript functions which may span multiple lines, and disallowing blank lines in JS is overly restrictive and ugly. But blank lines within JSXText nodes *should* start new blocks, somehow. So the following contrived example should be allowed:

```markdown
# This is a header

This is a paragraph.

<Foo
  render={() => {
    const foo = getFoo();
    const bar = getBar();

    enable(foo, bar);

    return (
      <span>

# This header starts block-based Markdown content

This only makes sense because it's the start of plain-text.

The blank lines within the JSX shouldn't end the JSX block.

      </span>
    );
  }}
/>
```

**Comment by sdegutis** [comment]
The JSX-based `htmlblock` implementation will probably have to use the Babel parser as described above to get the JSXText nodes out of this, stop block-based parsing at the end of the complete JSX expression, and resume parsing at each text node. In other words, the full length of the JSX expression will determine the `lines` tuple in the `htmlblock` token that it pushes.

Because other blocks can be nested, it *seems* (assuming my understanding of block-based plugins is correct) that we should use `state.parser.tokenize(state, startLine, endLine, true)` in order to enable the parsing of headers, paragraphs, block-quotes, etc. within a JSX block. (Btw, the last boolean argument is no longer used by `tokenize`, and should be removed from the docs.)

That said, I'm not really sure what values `startLine` and `endLine` should be. The docs are ambiguous about whether they represent the start/end of the entire JSX expression, the start/end of the JSX portion before hitting the first JSXText node, or the start/end of the first JSXText node.

To deal with *inline* Markdown content within a JSX block, it can probably use the same algorithm described above for parsing inline JSX via the new `htmltag` rule. To differentiate between whether the inline algorithm or this block-based tokenize-continuation should be used, maybe we can get away with just looking for whether there's a single newline (`\n`) in the JSXText node's string. That might well just be enough.

**Comment by sdegutis** [comment]
Here's an interesting edge-case:

```jsx
<Foo
  render={() => (
    <>

This is *block-based* Markdown.

This is {someJsVariable} split by {anotherJsVariable} JSX-based interpolation.

    </>
  )}
/>
```

This will result in three JSXText nodes:

- `'\n\nThis is *block-based* Markdown.\n\nThis is '`
- `' split by '`
- `' JSX-based interpolation.\n\n    '`

The first problem is that the middle node does *not* contain any newlines, so it wouldn't trigger block-based parsing.

The bigger problem is that all three nodes are technically part of the same block. The algorithm I described above wouldn't catch that semantic detail, and would probably render it all wrong.

**Comment by sdegutis** [comment]
To correctly determine in that scenario that the inner content should be considered a sub-block, we can look for JSXFragments or JSXElements whose children array begins with and ends with JSXText elements, and if the first one starts with `/\n\n+/` and the second ends with `/\n\n+/`, then it's a block. This algorithm should work just fine in all cases, because according to the [JSX AST spec](https://github.com/facebook/jsx/blob/master/AST.md), these are the only contexts JSXText nodes can occur.

**Comment by sdegutis** [comment]
The regex isn't necessary, we can just use:

```js
firstTextNode.startsWith('\n\n') &&
 lastTextNode.endsWith  ('\n\n')
```

**Comment by sdegutis** [comment]
That solution will also work when there are nested JSX expressions/fragments, such as:

```jsx
<Foo
  render={() => (
    <>

Nested inline <span>{jsxExpression}</span> within a block.

    </>
  )}
/>
```

This works because each JSXExpression or JSXFragment has its own children, so visiting each is independent of the linear order of the tokens. Yay for ASTs.

**Comment by sdegutis** [comment]
However, this situation is confusing:

```jsx
This paragraph contains *an inline <Foo render={() => (<>

# This is block Markdown content inside inline JSX

</>)}/> JSX block*, right in the middle of the paragraph.
```

What should this do? This would result in illegal, nonsensical HTML.

I suggest the JSX plugin just issue a warning, or possibly fail to compile with strict enough settings.

**Comment by sdegutis** [comment]
I'm going to trudge through a rough implementation of this today. There's a few questions I still have, hoping someone can offer some clarity around them:

- In the block parser docs, it says to use `state.parser.tokenize(state, startLine, endLine)` for recursive block parsing. What precisely do startLine and endLine represent? Is it the beginning and end of the inner Markdown within my block content? Or is it the full area of the JSX's block content I'm currently parsing, including non-Markdown text?

- Am I allowed to store state directly on the parser in some reserved pattern of non-clashing keys? If I use file-local variables, then multiple parsers cannot be run simultaneously. But maybe that's a non-issue and file-local variables are the way for plugins to store state between tokenization?

**Comment by sdegutis** [comment]
From the official JSX spec, it looks like the only valid characters that can trigger entry into JSX parsing are `<` and `{`. It looks like these two characters already fall through to the `htmltag` level of precedence, so as long as we can store the JSXExpression state safely somewhere, we can determine whether this represents a trigger character marking the beginning of further JSX processing. Thus we don't need the above described plan of having two phases and two rules for inline JSX parsing, we can safely just hijack the single `htmltag` rule.

**Comment by sdegutis** [comment]
Another question:

* While in block-parsing mode (i.e. `htmlblock`), how do we let `remarkable` know to tokenize patches of *inline Markdown* within the block? For example:

```jsx
<HtmlBlock render={() => <>This is *inline Markdown*.</>}/>
```

**Comment by sdegutis** [comment]
Answered one of my questions:

> Am I allowed to store state directly on the parser in some reserved pattern of non-clashing keys?

Yes, in `state.env`. Docs say it's "a namespaced data key-value store to allow core rules to exchange data". From looking at the source of built-in `remarkable` rules, it looks like "namespaced" just means that you should find a key similar enough to your rule name that it probably won't clash. Good enough for me.

**Comment by sdegutis** [comment]
Just finished the JSX implementation of `htmltag`! The function uses the algorithm described in this issue. It fully understands arbitrary arbitrarily nested JSX within Markdown! It depends on `@babel/parser` and `@babel/traverse`.

Working on `htmlblock` now.

**Comment by sdegutis** [comment]
There's an interesting conflict with blockquote rule.

Given this sample code that I've been working with:

```markdown
*test* <span
  qux={() => {
    return 3 + qux2(<>~~yes~~</>);
  }}
  render={
    <i>
      *yes* {<>**no**<k>*sup*</k></>} *welp*
    </i>
  }> *hi*</span> foo <u>*bar*</u>
```

Correctly translates to:

```jsx
<p><em>test</em> <SPAN
  QUX={() => {
    RETURN 3 + QUX2(<><del>yes</del></>);
  }}
  RENDER={
    <I>
<em>yes</em> {<><strong>no</strong><K><em>sup</em></K></>} <em>welp</em>
</I>
  }> <em>hi</em></SPAN> foo <U><em>bar</em></U></p>
```

But it's a common JSX idiom to put the closing `>` on its own line to help with indentation:

```markdown
*test* <span
  qux={() => {
    return 3 + qux2(<>~~yes~~</>);
  }}
  render={
    <i>
      *yes* {<>**no**<k>*sup*</k></>} *welp*
    </i>
  }
  > *hi*</span> foo <u>*bar*</u>
```

This turns into:

```jsx
<p><em>test</em> &lt;span
qux={() =&gt; {
return 3 + qux2(<><del>yes</del></>);
}}
render={
<I>
<em>yes</em> {<><strong>no</strong><K><em>sup</em></K></>} <em>welp</em>
</I>
}</p>
<blockquote>
<p><em>hi</em>&lt;/span&gt; foo <U><em>bar</em></U></p>
</blockquote>
```

It's clear the blockquote rule is taking precedence here, which is why the `htmltag` doesn't see the full expression but only the inner ones (because the full expression is missing a closing `>` symbol and is thus not a valid JSX expression).

I'm not really sure how to combat this. Maybe move `htmltag` to a higher precedence than `blockquote` (which is by default the highest)? I imagine that could have significant unexpected repercussions though...

**Comment by sdegutis** [comment]
Well first of all my solution involving precedence makes no sense, because blockquote is block-based and htmltag is inline-based.

But it seems to be an inherent property of blockquote syntax in Markdown that it doesn't require a newline to end the previous block, so that:

```markdown
Testing
> this
```

turns into:

```html
<p>Testing</p>
<blockquote><p>this</p></blockquote>
```

This means this JSX idiom isn't allowed within multi-line inline JSX unless we also change the semantics of blockquote to account for it somehow. But this seems low priority, since inline JSX expressions that span multiple lines probably won't be very common, and if they are, they can just avoid this syntax.

That said, it should be kept in mind when implementing htmlblock which may also have a similar issue.

**Comment by sdegutis** [comment]
I'm really stuck on how exactly to implement block-based rules that can contain nested blocks (paragraphs, lists) as well as nested inline content in the areas that are *not* part of the nested blocks. I'm having trouble understanding the docs and the built-in block syntaxes.

So for example, take this line-numbered Markdown (the numbers aren't part of the source):

```jsx
[0] <BlockElement someAttr={() => <>This is *inline markdown*</>} render={() => (
[1] 
[2] - This is an unordered
[3] - list containing some
[4] - simple <Box/> inline JSX
[5] 
[6] )}/>
```

In this case, I *think* that the nested-block-parsing aspect of this involves having the plugin *eventually* call `state.parser.tokenize(state, 1, 5, true)`, which will find a list on lines 2-4 and some inline JSX on line 4.

Does that sound right? Is that how to do nested block-based parsing in `remarkable`?

And if so, how does it give line 0 to the parser so that it can find the inline Markdown in it? Do we emit these 3 tokens?

- 'content' with `<BlockElement someAttr={() => <>`
- 'inline' with `This is *inline markdown*`
- 'content' with `</>} render={() => (`

**Comment by sdegutis** [comment]
Ok, just did some experiments and looked through parser_block.js a bit to figure some of this out.

In `state.parser.tokenize(state, startLine, endLine)`:

- `startLine` is inclusive, or the line to start at the beginning of
- `endLine` is exclusive, or the beginning of the line *after* the last one to parse
- parsing resumes on `state.line`
- the list rule seems to be setting `state.line` to the value we passed for `endLine`

So, running:

```js
state.parser.tokenize(state, 4, 5, true);
state.parser.tokenize(state, 3, 4, true);
state.line = 2;
```

on the above code, results in:

```html
 <ul>
<li>simple <BOX/> inline JSX</li>
</ul>
<ul>
<li>list containing some</li>
</ul>
<ul>
<li>This is an unordered</li>
<li>list containing some</li>
<li>simple <BOX/> inline JSX</li>
</ul>
<p>&lt;/&gt;)}/&gt;</p>
```

**Comment by sdegutis** [comment]
This seems to prove that we can and should use `state.parser.tokenize` using the algorithm described above involving finding all Babel sub-expressions containing JSXText children, and checking the first and last child for double-newlines to see if it should be interpreted as a block. If so, the line numbers that it starts at and ends at should be figured out (somehow), and we should run the tokenizer on it. Since we immediately get control of the parser again starting at `endLine`, we can do this in a loop, once for each verified nested block.

Then we'll also know what chunks of lines of our full block are *not* nested blocks, and at this point we know for sure that the remaining blocks of lines contain a mixture of JSX and inline Markdown.

Originally I was hoping we could just return these entire blocks as 'inline' nodes so that `remarkable` will continue parsing as normal and trigger our `htmltag` rule, so that we don't have to do double work. But neither `<BlockElement someAttr={() => <>This is *inline markdown*</>} render={() => (<>` nor `</>)}/>` are valid JSX elements by themselves, so the `htmltag` rule can't be reused.

Instead, I think we'll have to go through each remaining JSXText node (that wasn't already dealt with as a nested Markdown block) and mark it as `inline` content, and finally send the remaining JSX chunks as `content` content, just like described above. There's a slight concern still in my mind that this either won't account for every character of our JSX expression, or that it might have some of the block-areas overlapping with some of the inline-tokens or content-tokens. But I'm pretty sure we've logically proven that this won't happen, it's just hard to put it into words right now.

**Comment by sdegutis** [comment]
My implementations of JSX-aware `htmlblock` and `htmltag` rules are complete.

The only thing that's left is rendering. Normally it would be done, since my plugin emits the same types of tokens (just more of them), with the same semantics, as the two built-in HTML rules. But there were two issues:

- Some tags aren't self-closing, like \<hr>. Enabling `xhtmlOut` fixes this fully.
- Other rule renderers are emitting HTML-style attributes, rather than React-style attributes, such as `td_open` using `<td style="text-align:right">` instead of `<td style={{textAlign:'right'}}>`.

The second issue can be addressed in one of two ways:

1. Have the JSX plugin override each rule with an almost-identical copy that emits proper JSX. This would result in a ton of duplication, would be a maintenance nightmare to keep the plugin in sync with remarkable itself, and would not respect overridden rendering rules by *other* plugins.

2. Modify remarkable itself to be aware of JSX, and switch on a JSX option to know which style of attrs to emit. This would need to either be aware of other styles (React isn't the only framework), or this aspect of the renderer would need to be made separately pluggable too.

Maybe I missed some options. But in case this is all there is, I'm leaning towards the second.

**Comment by sdegutis** [comment]
I overestimated how fragile and difficult it would be to override the HTML-specific attributes in renderers. That part is finished and it only took about 14 lines. If users want to use other plugins that emit non-JSX attributes, they'll have to manually adjust their output, which is probably reasonable.

**Comment by sdegutis** [comment]
My JSX plugin is now finished. It enables Remarkable to understand JSX completely, and emit React-friendly code.

This issue had two purposes:

1. As a place where I can ask questions about how to implement this plugin.
2. As a suggestion to consider whether JSX should be included into Remarkable.

The first purpose is no longer necessary now that I've finished developing the plugin. This issue contains a lot of specifics on Remarkable plugin development that may be able to help other people.

The question of whether to include my plugin as a core part of Remarkable still stands as a possibility. Because of Remarkable's excellent architecture, my plugin is able to stand alone completely and doesn't need any special integration.

That said, it may be worth including it anyway. Through the popularity of projects like React, JSX is gaining mainstream adoption rapidly, and Markdown + JSX is becoming more and more popular as evident by the fact that [MDX](https://mdxjs.com) is getting 100k downloads per week and thousands of projects using it. Having native JSX support would be yet another advantage for Remarkable over other Markdown renderers.

So that's the question I pose to the authors and maintainers here, and the only question remaining in this issue.

/cc @TrySound, @jonschlinkert et al.

**Comment by jonschlinkert** [comment]
This is fantastic! Really sorry I haven't comment on this yet, I've had a bad cold this past week. 

> The question of whether to include my plugin as a core part of Remarkable still stands as a possibility.

I'm not necessarily opposed to it, but I'm wondering if - instead - we should create a site like https://gulpjs.com/ with a `plugins` page, where you can search for remarkable plugins. IMHO, your plugin is a great example of what's possible. Maybe we can get some contributors to help create a website 😉

**Comment by sdegutis** [comment]
@jonschlinkert The readme already contains a link to an NPM search for Remarkable plugins. But they're hard to search through. A curated list of top recommended plugins might be better. And that could just as well be on the readme. That said, I personally think JSX support is more on the level of HTML support than on the level of plugins, even though technically it can be implemented externally.

**Comment by jonschlinkert** [comment]
> A curated list of top recommended plugins might be better.

Yes, absolutely.

> I personally think JSX support is more on the level of HTML support than on the level of plugins, even though technically it can be implemented externally.

Many times in the past with other projects, we've started by externalizing features as plugins, then later we moved the plugins features into "core" because of the popularity. IMHO this is the approach we should take, as it works really well. 

I'd be happy to mention your plugin on the readme, and/or make it a recommended plugin, but I'd need some evidence that JSX support would be needed by a significant percentage of users before moving it into core. 

cc @TrySound @doowb

**Comment by sdegutis** [comment]
👍

**Comment by TrySound** [comment]
mdx is quite popular. I am happy to mention it in readme of it's possible to implement a separate plugin. @jonschlinkert As core plugin it's possible to add separate entry point similar to `remarkable/linkify`.

**Comment by sdegutis** [comment]
One thing to consider: my plugin for Remarkable does not have all the features that MDX has, which mostly have to do with integrating into a webpack build setup. The plugin I wrote is a simple transformer of Markdown + JSX => JSX (as opposed to the traditional Markdown + HTML => HTML).

**Comment by jonschlinkert** [comment]
@sdegutis did you link to the code anywhere. If not, could you add a link for us to review. If you did, sorry I didn't see one, I scanned a couple of times.

**Comment by sdegutis** [comment]
@jonschlinkert I just found out about Markdown-it. What is the relationship between Remarkable and Markdown-it? I see a few confusing facts. Markdown-it continues code commits by the same code authors as Remarkable starting around December 2014, whereas around that time Remarkable slowed down significantly. Also your name is in the readme on the first commit even though I don't see a single code commit of yours until after Markdown-it was created.

**Comment by jonschlinkert** [comment]
A troll comment was deleted. 

@sdegutis first, you didn't reply to my request to add code. I would have gladly helped you finish what you're doing. 

Also, I received your email. Wow, it was... um, not very kind. 

See https://github.com/jonschlinkert/remarkable/issues/363
