### ISSUE TITLE
Image in render pane only appears when I paste copied image inline in script.

### ISSUE THREAD

**Issue by ployt0** [jonschlinkert/remarkable#370]
My first use case worked, I'd paste the image directly into the editor. Great.

Now I have a bunch of screen cap's that don't require editing and when I drag and drop I helpfully get the full path but no image in markdown or render pane.

Fair enough I thought. Now when I click insert image I fill in all the boxes and get some lovely valid markdown.

Sadly this isn't enough for the render pane, and probably is sub-optimal for portability; for while they share a directory with the markdown file the markdown in no-way captures a copy to own. Not sure if the latter is good or bad, but the setup described _is_ portable and _should_ be rendered in the RHS.

**Comment by DiscoNova** [comment]
Your problem seems to be with [Remarkable -editor](https://github.com/jamiemcg/Remarkable) which is a completely different project from completely different team.
