### ISSUE TITLE
When I click a link it opens in the RHS render pane without a back button

### ISSUE THREAD

**Issue by ployt0** [jonschlinkert/remarkable#371]
I can work-around by clicking the undo button and redo, but this feels very wrong.

I thought this was both an editor and renderer application. Therefore I would like not to have to modify the source to return to viewing it. Could a back button, or opening www links in the default browser be considered as improvements?

**Comment by DiscoNova** [comment]
Your problem seems to be with [Remarkable -editor](https://github.com/jamiemcg/Remarkable) which is a completely different project from completely different team.
