### ISSUE TITLE
Uncaught ReferenceError: Remarkable is not defined

### ISSUE THREAD

**Issue by asd-a** [jonschlinkert/remarkable#373]
when i use it in browser with cdn
i can't use `var md =  new Remarkable();` because of the error
why?and how to deal with?

**Comment by TrySound** [comment]
It's `new remarkable.Remarkable()`

**Comment by DoctaRay** [comment]
I am getting the same error. Inside my script tag, I have the following
```javascript
import * as remarkable  from 'https://cdnjs.cloudflare.com/ajax/libs/remarkable/2.0.0/remarkable.min.js';
    var md = new remarkable.Remarkable();  
    $(document).ready(function(){
      $("#abstract").append(md.render("# Remarkable rulezz!"));
    }); 
    console.log(md.render("# Remarkable rulezz!"))
```

Has anyone found a solution yet?

**Comment by TrySound** [comment]
Yes, because remarkable.min.js is not es module. It's UMD and work only with AMD, CommonJS and as IIFE wrapper.
Here's esm bundle for browser
https://unpkg.com/browse/remarkable@2.0.0/dist/esm/index.browser.js
