### ISSUE TITLE
Some entities not rendered correctly in the browser

### ISSUE THREAD

**Issue by kasperpeulen** [jonschlinkert/remarkable#380]
I have a unit test in node:

```js
expect(new Remarkable().renderInline('&euro;')).toEqual('€')
```

which passes, but in the browser it is rendered as `&amp;euro`

Which causes it to look like:

![image](https://user-images.githubusercontent.com/1035299/82795576-7f752500-9e74-11ea-9b89-a585893b75aa.png)

**Comment by kasperpeulen** [comment]
It seems that this piece of code is the problem:
`lib/common/entities.browser.js`

```
var textarea;

export function decodeEntity(name) {
  textarea = textarea || document.createElement('textarea');
  textarea.innerHTML = '&' + name;
  return textarea.value;
}
```

It should be:
```
```
var textarea;

export function decodeEntity(name) {
  textarea = textarea || document.createElement('textarea');
  textarea.innerHTML = '&' + name + ';';
  return textarea.value;
}
```

**Comment by TrySound** [comment]
Good catch! Would you like to send PR?

**Comment by kasperpeulen** [comment]
Yes, done now.

**Comment by MatthiasSaihttam** [comment]
It looks like this issue has been fixed and can be closed.
