### ISSUE TITLE
Adding plugins to snap

### ISSUE THREAD

**Issue by bitdivine** [jonschlinkert/remarkable#383]
Thank you for providing a desktop version of Remarkable as a snap package.  Is there a way of adding plugins to the desktop app?  I don't see an option for doing so in the menus or in the [plugin docs](https://github.com/jonschlinkert/remarkable/blob/master/docs/plugins.md).

**Comment by theZetrax** [comment]
I don't think this is related to the remarkable linux markdown app, I think you're looking for this https://snapcraft.io/install/remarkable/ubuntu

**Comment by DiscoNova** [comment]
I don't think this relates to this project either (we're currently in the remarkable-parser repository's issue tracker) ... Believe you me, I've mistaken the projects for one another in the past too ... even though I know very well that there are more than one "remarkable"-projects in Github :D

**Comment by doowb** [comment]
Correct, this project is not related to a snap package.

**Comment by bitdivine** [comment]
Ah, thank you for the pointer.  Sorry for the noise!
