### ISSUE TITLE
Making clickable link with angle brackets?

### ISSUE THREAD

**Issue by jackhodgson** [jonschlinkert/remarkable#392]
As a longtime users of Markdown I may be using a syntax that is deprecated, but...

I regularly create a simple, clickable link by enclosing the URL in angle brackets. But using Remarkable I can't get these to render as links. 

Do I need some extra option set? Is this not supported? 

Thanks.

**Comment by doowb** [comment]
The syntax you're describing is for [autolinks](https://spec.commonmark.org/0.29/#autolink).

If you don't have a scheme in the URL, then the link is treated as regular text and the angle brackets are html encoded.
See [this demo](https://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiMlMjBBdXRvbGlua3MlNUNuJTVDbkZvciUyMG1vcmUlMjBpbmZvcm1hdGlvbiUyMHNlZSUyMHRoZSUyMCU1QmNvbW1vbm1hcmslMjBzcGVjJTVEKGh0dHBzOi8vc3BlYy5jb21tb25tYXJrLm9yZy8wLjI5LyNhdXRvbGluayklNUNuJTVDbiMjJTIwVmFsaWQlMjBhdXRvbGluayU1Q24lNUNuJTYwJTYwJTYwJTVDbiUzQ2h0dHBzOi8vZ2l0aHViLmNvbS9qb25zY2hsaW5rZXJ0L3JlbWFya2FibGUlM0UlNUNuJTYwJTYwJTYwJTVDbiU1Q24lM0NodHRwczovL2dpdGh1Yi5jb20vam9uc2NobGlua2VydC9yZW1hcmthYmxlJTNFJTVDbiU1Q24jIyUyMEludmFsaWQlMjBhdXRvbGluayU1Q24lNUNuJTYwJTYwJTYwJTVDbiUzQ2dpdGh1Yi5jb20vam9uc2NobGlua2VydC9yZW1hcmthYmxlJTNFJTVDbiU2MCU2MCU2MCU1Q24lNUNuJTNDZ2l0aHViLmNvbS9qb25zY2hsaW5rZXJ0L3JlbWFya2FibGUlM0UlMjIsJTIyZGVmYXVsdHMlMjI6JTdCJTIyaHRtbCUyMjpmYWxzZSwlMjJ4aHRtbE91dCUyMjpmYWxzZSwlMjJicmVha3MlMjI6ZmFsc2UsJTIybGFuZ1ByZWZpeCUyMjolMjJsYW5ndWFnZS0lMjIsJTIybGlua2lmeSUyMjpmYWxzZSwlMjJsaW5rVGFyZ2V0JTIyOiUyMiUyMiwlMjJ0eXBvZ3JhcGhlciUyMjp0cnVlLCUyMl9oaWdobGlnaHQlMjI6dHJ1ZSwlMjJfc3RyaWN0JTIyOmZhbHNlLCUyMl92aWV3JTIyOiUyMmh0bWwlMjIlN0QlN0Q=) for an example.

Other than autolinks, you can use the `[label](url)` syntax.

**Comment by jackhodgson** [comment]
Thanks for the reply. You were, of course, exactly right. Your answer prompted me to do more tests, and I found that the problem was that my markdown text was being corrupted by the source I was getting it from. Not really relevant to this Issue or to Remarkable. Thanks again.
