### ISSUE TITLE
Debian package does not work in Linux Mint 20

### ISSUE THREAD

**Issue by Aliuken** [jonschlinkert/remarkable#400]
I get an error while trying to install Remarkable in Linux Mint 20 with the .deb package.

It cannot find the dependency gir1.2-webkit-3.0

Is that planned to be solved?

**Comment by shufps** [comment]
Also does not work in kubuntu 20.04.

There are bugs open for several years and no solution - so I guess not ;-)

**Comment by doowb** [comment]
I think you're looking for the [Remarkable Linux application](https://github.com/jamiemcg/remarkable).

Since this repository is for the `remarkable` Node.js package, I'm going to close this issue. If I'm mistaken, please feel free to let me know and I'll reopen the issue.
