### ISSUE TITLE
Cannot use `CTRL+C` to copy selected text in preview

### ISSUE THREAD

**Issue by ijash** [jonschlinkert/remarkable#409]
Hi, I cannot use the keyboard shortcut **ctrl+c** for copying a selected text in live preview pane. If not yet implemented, please add it as a ferature in next release.

I am using desktop version 1.87 on linux 
here's my spec:

> System:
  Host: LM-PC Kernel: 5.4.0-74-generic x86_64 bits: 64 compiler: gcc 
  v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin 4.4.4 dm: LightDM 1.26.0 
  Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:
  Type: Desktop System: Gigabyte product: Z270X-UD3 v: N/A serial: <filter> 
  Mobo: Gigabyte model: Z270X-UD3-CF v: x.x serial: <filter> 
  UEFI: American Megatrends v: F7 date: 07/07/2017 
CPU:
  Topology: Quad Core model: Intel Core i7-7700K bits: 64 type: MT MCP 
  arch: Kaby Lake rev: 9 L2 cache: 8192 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 67200 
  Speed: 800 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 802 6: 800 7: 800 8: 800 
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] vendor: ASUSTeK driver: nvidia 
  v: 390.143 bus ID: 01:00.0 chip ID: 10de:1b81 
  Display: x11 server: X.Org 1.20.8 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa 
  resolution: 1920x1080~60Hz, 1366x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 390.143 
  direct render: Yes

**Comment by DiscoNova** [comment]
Wrong remarkable ... You're looking for Remarkable (with capital "R") ... https://github.com/jamiemcg/Remarkable

**Comment by doowb** [comment]
Thanks @DiscoNova
