### ISSUE TITLE
Mac desktop app - export pdf

### ISSUE THREAD

**Issue by jacquesfayollemines** [jonschlinkert/remarkable#428]
When you export a note to pdf, it takes the name of the note as filename of the pdf. But if you export a different note juste after, it always take the name of the previous note as filename ...

**Comment by DiscoNova** [comment]
Umm... the report seems to refer to another project, [Jamie McGowan's Remarkable editor](https://github.com/jamiemcg/Remarkable) which, regardless of sharing a name with this project, is unrelated.

If I am mistaken, my apologies. Admittedly this is unfortunate that two projects share a name, but ... this has been the case for years now. It also doesn't help that Google search for "remarkable" does seem to return results from both projects making it look as if they're two sides of the same coin :-/

**Comment by doowb** [comment]
@DiscoNova is correct. You're looking for the other project.
