### ISSUE TITLE
Support for WikiLink syntax

### ISSUE THREAD

**Issue by asb** [jonschlinkert/remarkable#93]
This is a feature request for WikiLink syntax as [supported by Github Wiki](https://help.github.com/articles/adding-links-to-wikis/). Basically this is the syntax used by Wikipedia `[[Link text | Link target]]`. I'd argue this is generally useful enough to be included as a supported extension, but otherwise it could be a good example of how to build a custom plugin (ref #48).

**Comment by boehs** [comment]
Via: https://github.com/nornagon/remarkable-wikilink/blob/master/index.js
